openapi: 3.0.0
info:
  title: API de Disciplinas e Planejamento
  version: 1.0.0
  description: Documentação da API de Disciplinas e Planejamento
paths:
  /disciplines:
    get:
      summary: Retorna todas as disciplinas
      responses:
        200:
          description: Lista de disciplinas retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Disciplines were found successfully!"
                  disciplines:
                    type: array
                    items:
                      $ref: '#/components/schemas/DisciplineDTO'

  /disciplines/getByID/{id}:
    get:
      summary: Retorna uma disciplina pelo ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Disciplina encontrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Discipline was found successfully!"
                  discipline:
                    $ref: '#/components/schemas/DisciplineDTO'

  /disciplines/getByName/{name}:
    get:
      summary: Retorna uma disciplina pelo nome
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        200:
          description: Disciplina encontrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Discipline was found successfully!"
                  discipline:
                    $ref: '#/components/schemas/DisciplineDTO'

  /protected/disciplines:
    post:
      summary: Cria uma nova disciplina
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisciplineDTO'
      responses:
        201:
          description: Disciplina criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Discipline created successfully!"
                  discipline:
                    $ref: '#/components/schemas/DisciplineDTO'

    delete:
      summary: Deleta todas as disciplinas
      responses:
        200:
          description: Todas as disciplinas foram deletadas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "All disciplines were deleted successfully!"

  /protected/disciplines/{id}:
    patch:
      summary: Atualiza uma disciplina pelo ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisciplineDTO'
      responses:
        200:
          description: Disciplina atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Discipline's field updated successfully!"
                  discipline:
                    $ref: '#/components/schemas/DisciplineDTO'

    delete:
      summary: Deleta uma disciplina pelo ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Disciplina deletada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Discipline was deleted successfully!"
  /planning:
    get:
      summary: Retorna todos os planejamentos
      responses:
        200:
          description: Lista de planejamentos retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Plannings fetched"
                  planning:
                    type: array
                    items:
                      $ref: '#/components/schemas/PlanningDTO'
    post:
      summary: Cria um novo planejamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: O nome do planejamento
                periods:
                  type: array
                  description: Lista de períodos associados ao planejamento
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Nome do período
                      disciplines:
                        type: array
                        description: Lista de disciplinas associadas ao período
                        items:
                          type: integer
              required:
              - name
              - periods
      responses:
        201:
          description: Planejamento criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Planning created!"
                  createdPlanning:
                    $ref: '#/components/schemas/PlanningDTO'
        400:
          description: Erro nos dados fornecidos
        409:
          description: Planejamento já existente com o nome fornecido
        500:
          description: Erro interno do servidor

    put:
      summary: Atualiza um planejamento existente, mas precisa do id do planajamento e também do id de cada period(frontend terá acesso através do get)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID do planejamento
                name:
                  type: string
                  description: Nome do planejamento
                periods:
                  type: array
                  description: Lista de períodos associados ao planejamento
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID do período
                      name:
                        type: string
                        description: Nome do período
                      disciplines:
                        type: array
                        description: Lista de disciplinas associadas ao período
                        items:
                          type: integer
              required:
              - id
              - name
              - periods
      responses:
        200:
          description: Planejamento atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Planning updated!"
                  updatedPlanning:
                    $ref: '#/components/schemas/PlanningDTO'
        400:
          description: Erro nos dados fornecidos
        404:
          description: Planejamento não encontrado
        500:
          description: Erro interno do servidor

  /planning/{id}:
    get:
      summary: Retorna um planejamento específico pelo ID
      parameters:
      - in: path
        name: id
        required: true
        description: ID do planejamento
        schema:
          type: integer
      responses:
        200:
          description: Planejamento encontrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Planning fetched"
                  planning:
                    $ref: '#/components/schemas/PlanningDTO'
        404:
          description: Planejamento não encontrado
        500:
          description: Erro interno do servidor
components:
  schemas:
    DisciplineDTO:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        name:
          type: string
        acronym:
          type: string
        available:
          type: boolean
        description:
          type: string
        pre_requisites:
          type: array
          items:
            type: string
        post_requisites:
          type: array
          items:
            type: string
        teacher:
          type: string
        schedule:
          type: string

    PlanningDTO:
      type: object
      required:
      - id
      - name
      - periods
      properties:
        id:
          type: integer
          description: ID único do planejamento
        name:
          type: string
          description: Nome do planejamento
        periods:
          type: array
          description: Lista de períodos associados ao planejamento
          items:
            $ref: '#/components/schemas/PeriodDTO'

    PeriodDTO:
      type: object
      required:
      - id
      - name
      - planningId
      - disciplines
      properties:
        id:
          type: integer
          description: ID único do período
        name:
          type: string
          description: Nome do período
        planningId:
          type: integer
          description: ID do planejamento ao qual o período pertence
        disciplines:
          type: array
          description: Lista de disciplinas do período
          items:
            $ref: '#/components/schemas/DisciplineInterface'

    DisciplineInterface:
      type: object
      required:
      - id
      - name
      - type
      - acronym
      - available
      - description
      - pre_requisites
      - post_requisites
      - teacher
      - schedule
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        acronym:
          type: string
        available:
          type: boolean
        description:
          type: string
        pre_requisites:
          type: array
          items:
            type: string
        post_requisites:
          type: array
          items:
            type: string
        teacher:
          type: string
        schedule:
          type: string
